
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'

import Header from './components/Header/Header'
import { store } from './store/store'
import '../styles/index.scss'

function App({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Ubyni</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Provider store={store}>
      {/* Header */}
      <Header/>
      {/* Body */}
      <main>
        <Component {...pageProps} />
      </main>
    </Provider>

  </>
}
  
export default App
