// import '../styles/globals.scss'
import '../styles/index.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Header from './components/Header/Header'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Ubyni</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {/* Header */}
    <Header/>
    {/* Body */}
    <main>
      <Component {...pageProps} />
    </main>

  </>
}
  
export default MyApp
